pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick

// Material colour roles generated by matugen
// (~/.config/matugen/templates/quickshell-colors.json). The file is watched, so
// a new wallpaper recolours the running shell. Defaults are Catppuccin Frappé,
// used until the file exists. Read colours through Theme, not from here.
Singleton {
    readonly property alias roles: adapter

    FileView {
        path: `${Quickshell.env("HOME")}/.local/state/quickshell/colors.json`
        watchChanges: true
        printErrors: false
        onFileChanged: reload()

        JsonAdapter {
            id: adapter

            // kitty/GTK tones (secondary_container at HSL lightness 15 and 30)
            property color shell_surface: "#232634"   // crust
            property color shell_highlight: "#414559" // surface0

            // on_surface/on_primary under other names: QML takes on_* for signal handlers
            property color shell_text: "#c6d0f5"      // text
            property color shell_text_on_primary: "#232634"

            property color outline: "#737994"         // overlay0

            property color primary: "#8caaee"         // blue
            property color secondary: "#99d1db"       // sky
            property color tertiary: "#ca9ee6"        // mauve
            property color error: "#e78284"           // red
        }
    }
}
